karser_recaptcha3:
    host: 'www.recaptcha.net'
    site_key: '%env(RECAPTCHA3_KEY)%'
    secret_key: '%env(RECAPTCHA3_SECRET)%'
    score_threshold: 0.5
    enabled: '%env(bool:RECAPTCHA3_ENABLED)%'