name: promo_quoter

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-11}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost --user='${MYSQL_USER:-app}' --password='${MYSQL_PASSWORD:-!ChangeMe!}'"]
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

#volumes:
###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
